### ISSUE TITLE
Dualis nicht mehr verfügbar nach Update der Dualis Website

### ISSUE THREAD

**Issue by blitzdose** [Bennik2000/DHBWStudentInformationApp#101]
Nach einem Update der DUALIS Website an der DHBW Karlsruhe funktioniert der Login nicht mehr in der App. (Anmeldung fehlgeschlagen) Wahrscheinlich wurde das Login-Verfahren geändert und ist nicht mehr mit der App kompatibel.

## Context
Android version: 1.1.6
App version: 10

**Comment by Bennik2000** [comment]
Danke fürs Mitteilen, in der Tat hat sich eine Kleinigkeit im Dualis geändert.

Das Update ist unterwegs.
