### ISSUE TITLE
Rapla Calendar for DHBW Mosbach 

### ISSUE THREAD

**Issue by joossm** [Bennik2000/DHBWStudentInformationApp#104]
## Feature Request

Could you please provide support for the Calendar from DHBW Mosbach?

This is an example ink:
https://rapla.dhbw.de/rapla/calendar?key=2a9Bq7PTVcTMvCSNwYoQRrO0GK9bccz-i39YnTK__wfzLf7zoDljz6ez6o-rF2Fsp4Cjn3VUMgfKBZ_BsAJvOcGkFsW49XkYpq5u9TSYXj8&salt=11988947&allocatable_id=rc71823f-f1e4-4513-951a-422037cf5c27#22

Thanks!

**Comment by Bennik2000** [comment]
Thanks for reporting this issue!

I will be working on this the next weeks but can't make any promises.

**Comment by fabbe0p** [comment]
Hi,
wär auch nice, wenn Karlsruhe gehen würde:)

**Comment by Bennik2000** [comment]
@fabbe0p dazu bräuchte ich einen Link vom Vorlesungsplan um die Daten abzurufen. Wenn Du mir einen geben könntest, kann ich es mir mal anschauen und ggf. implementieren.

**Comment by fabbe0p** [comment]
Hi ;)
Hier die Links, ich habe alles versucht, ging aber nix, auf Dualis haben wir leider keinen Vorlesungsplan. 

Html: https://rapla.dhbw-karlsruhe.de/rapla?page=calendar&user=ahrensb&file=TEL20B1

ICAL: https://rapla.dhbw-karlsruhe.de/rapla?page=ical&user=ahrensb&file=TEL20B1

Vg und schon mal vielen Dank fürs anschaun

**Comment by Bennik2000** [comment]
@joossm Die Unterstützung für die DHBW Mosbach wird mit dem nächsten Update kommen (#105)

---

@fabbe0p Für die Links der DHBW Karlsruhe muss in der Rapla Konfiguration etwas geändert werden, sonst kann die App den Plan nicht interpretieren. 
Die Konfiguration in Rapla heißt „Mouse-over“ und findet sich unter dem Button „Anzeige“. Am besten, Du schreibst eine E-Mail an den entsprechenden Dozenten bzw. Sekretariat.

Der ICAL Link wird in der nächsten Version teilweise unterstützt. Manche Vorlesungen werden jedoch nicht angezeigt, da die App das iCAL Format nicht vollständig implementiert.

**Comment by fabbe0p** [comment]
Hi;)
Der Haken war schon gesetzt, passt das so? Scheint ein anderes Problem zu sein.
Vg![IMG_20211005_125401172_HDR.jpg](https://user-images.githubusercontent.com/90555403/136010195-4848bc45-a3ff-45b2-bcc7-467c6f127290.jpg)

**Comment by Bennik2000** [comment]
Wie genau Rapla konfiguriert sein muss kann ich leider nicht sagen. 
Die oben genanntee Einstellung wurde mir so von einem Professor genannt. Was wichtig für die Funktion ist, ist das Tooltip, wenn mit der Maus über eine Vorlesung gefahren wird. Wie in diesem Screenshot gezeigt: 
![grafik](https://user-images.githubusercontent.com/8039939/136017642-23fa4910-b2e9-4e08-804e-ab8124b37d72.png)


Das ist leider bei deinem Link nicht der Fall, daher kann die App den Vorlesungsplan nicht lesen. Vielleicht bekommt ihr Rapla so konfiguriert, dass das Tooltip angezeigt wird.

**Comment by joossm** [comment]
Hey @Bennik2000,

danke dir!
Wann gibt's das neue Update?

**Comment by Bennik2000** [comment]
Die Version 1.1.10  ist seit ungefähr zwei Wochen im AppStore und im PlayStore.

**Comment by joossm** [comment]
Hey,

die App zeigt leider den Fehler das der Plan nicht angezeigt werden kann.

Kalenderlink:
https://rapla.dhbw.de/rapla/calendar?key=L1Upk4UQHNN-E2eHtodVuT0y8JZsWG-fqltFk3YmKxdRGUzqSI6c3EM-BvlwDN0GARuS_HVIIikzd-ymefwzJw&salt=361925764

**Comment by Bennik2000** [comment]
@joossm Danke für den Kommentar, ich habe ein neues Issue dafür eröffnet. (#120 )
