### ISSUE TITLE
Some Calendar Fields are not displayed in App

### ISSUE THREAD

**Issue by FrederikWolter** [Bennik2000/DHBWStudentInformationApp#117]
## Current Behavior
Some calendar fields are not displayed in App calendar.
Calendar of DHBW Mannheim shows information like '_room_' and '_information if lecture is online_' besides the lecture´s name:
> ![grafik](https://user-images.githubusercontent.com/35914049/141074475-2bfb06f2-00c5-4d54-b5d3-d4afbb3ff44b.png)
In the app this information is missing in the overview and detail-view (when clicked on the lecture) .

## Context
Android version: 11
App version: 1.1.11
This bug/missing information could lead to problematic situations and damages the benefit of the app.

**Comment by Bennik2000** [comment]
Thanks for this report. Depending on the location where you study this information is displayed already. Could you provide an url to your schedule? Then I could look into it.

**Comment by FrederikWolter** [comment]
Hi thanks for the fast reply,
here a link to my current schedule:
https://vorlesungsplan.dhbw-mannheim.de/index.php?action=view&gid=3067001&uid=8062001

**Comment by Bennik2000** [comment]
The app reads the schedule from the iCAL of your class. Unfortunately the iCAL link does not provide the information if the class is online.

The best guess is to parse the title and check if it contains the word "online". The app already does this and it gets improved in the next update. 

Thanks for sharing this bug but for now I can't do very much about it.
