### ISSUE TITLE
Studenplan lädt nicht 

### ISSUE THREAD

**Issue by lukasg02** [Bennik2000/DHBWStudentInformationApp#118]
Hallo, mein Vorlesungsplan lädt auf meinem iPhone nicht, auch nach mehrmaliger Neuinstallation. Auf meinem iPad funktioniert alles ohne Probleme. Hier der Link:
http://193.196.6.13/rapla?page=calendar&user=Krieg&file=TEA20
Edit: auf dem iPad geht es jetzt auch nicht mehr

**Comment by Lionhunt3r** [comment]
Kann ich mich anschließen. Bei mir funzt es auch nicht!

**Comment by Bennik2000** [comment]
@lukasg02 ich kann das Problem nicht reproduzieren, der Vorlesungsplan wird korrekt angezeigt. Sowohl auf Android, als auch auf iOS. Stelle sicher, dass du die aktuellste App Version hast und der Link korrekt eingegeben wurde (auch das `http://` am Anfang vom Link ist notwendig).

![Screenshot_1645887889](https://user-images.githubusercontent.com/8039939/155847996-bccadaaa-e258-495b-aaad-4c568a72339e.png)
.

**Comment by Bennik2000** [comment]
@Lionhunt3r Falls du einen anderen Link verwendest, öffne bitte ein neues Issue und trage den Link ein. Dann kann ich mir das Problem anschauen.
