### ISSUE TITLE
Mit Kalender synchronisieren

### ISSUE THREAD

**Issue by domhel** [Bennik2000/DHBWStudentInformationApp#122]
## Feature Request

**Is your feature request related to a problem? Please describe.**
nicht wirklich

**Describe the solution you'd like**
Den Stundenplan mit Google Calendar oder sonstigen synchronisieren (CalDAV synch Format)

Es ist bestimmt aufwendig und du hast wahrscheinlich keine Zeit dafür. Wäre aber mega nützlich

**Comment by Bennik2000** [comment]
Sowas ist möglich und wird bei uns im Kurs auch (zumindest in den früheren Semestern) so gemacht. Dazu hat ein Kommilitone von mir ein Skript geschrieben. 

Ich weiß nicht, wie gut du dich mit Python Scripts auskennst, hier wäre das Script: https://github.com/codingHahn/dhbw-ical. 
Es erfordert leider eine gewisse Infrastruktur und hat noch 2-3 kleine Bugs geht aber wahrscheinlich in die Richtung was du suchst.

**Comment by LukasLJL** [comment]
Für CalDAV hat ein Kommilitone, dass hier in Java geschrieben: https://github.com/grossamos/RaplaCalendarConverter
Er hat aber vor das ganze mal komplett neu zu machen. Vielleicht hilft das :D
