### ISSUE TITLE
Vorlesungsplan funktioniert nicht mehr

### ISSUE THREAD

**Issue by SgtMate** [Bennik2000/DHBWStudentInformationApp#132]
## Welche Quelle nutzt du für den Vorlesungsplan?

- [x] Rapla
- [ ] Dualis
- [ ] DHBW Mannheim
- [ ] iCAL Kalender

## Link zum Vorlesungsplan (Wichtig!)

```
https://rapla.dhbw-stuttgart.de/rapla?key=txB1FOi5xd1wUJBWuX8lJrog1ZNPBrE7IVuW7j2dZDqjlvUVaOUAHGMIpismBZua&today=Heute
```

**Comment by KindOfGod** [comment]
Potenziell gleiches Problem wie hier (https://github.com/Bennik2000/DHBWStudentInformationApp/issues/120). Die DHBW hat vielleicht wieder querry parameter geändert.
Es wird im Sekretariat nachgehackt.

**Comment by SgtMate** [comment]
Jo hab sowas schon vermutet. 
Danke für die Antwort. 
Ich werde vermerken wenn wieder läuft.

**Comment by SgtMate** [comment]
Fehler ist Behoben.

**Comment by Bennik2000** [comment]
@SgtMate was war das Problem?

**Comment by SgtMate** [comment]
> @SgtMate was war das Problem?

Der Vorlesungsplan hat nicht geladen. Vor ein paar Tagen hat es Plötzlich wieder funktioniert. Keine Ahnung wieso.
