### ISSUE TITLE
Anmeldung bei Dualis schlägt seit einiger Zeit fehl

### ISSUE THREAD

**Issue by Sarahsadepaul** [Bennik2000/DHBWStudentInformationApp#134]
Meinen Vorlseungsplan kann ich auf dem einen Handy (Iphone 12) anschauen. Auf dem anderen (Iphone 14) nicht. Fehlermeldung: Keine Verbindung (bestehende Internet Verbindung). Auf beiden Handys kann ich mich nicht bei Dualis anmelden. Fehlermeldung: Anmeldung fehlgeschlagen.

**Comment by technochicken** [comment]
Problem besteht auch an Smartphones an der DHBW-Stuttgart-Horb. Fehlermeldung bei Stundenplan "Keine Verbindung" auch das Anmelden in Dualis über die App ist nichtmehr möglich.

**Comment by Sarahsadepaul** [comment]
Ich konnte das mit dem Vorlesungsplan lösen indem ich die App gelöscht habe und neu installiert habe (inkl. Anmeldung über Rapla bei der App). 
dualis funktioniert leider noch nicht.

**Comment by technochicken** [comment]
An der DHBW-Stuttgart/Horb ist leider kein ralpla Zugang möglich(nach meinem Wissensstand), auch eine Neuinstallation hat das Problem nicht gelöst.
