### ISSUE TITLE
Dualis Login (iOS) funktioniert nicht

### ISSUE THREAD

**Issue by xdavld** [Bennik2000/DHBWStudentInformationApp#136]
Der Dualis Login auf iOS Geräten funktioniert leider nicht mehr.

**Comment by xdavld** [comment]
Siehe Issue #134

**Comment by technochicken** [comment]
Auf dem AppStore ist nur die Version 1.1.16 verfügbar. Der entsprechende fix ist in der 1.1.17. @Bennik2000 kannst du den fix auch auf dem AppStore veröffentlichen?

**Comment by xdavld** [comment]
Login funktioniert wieder, danke! 

#135
