### ISSUE TITLE
Change default dualis page to "Exams"

### ISSUE THREAD

**Issue by CodingMarco** [Bennik2000/DHBWStudentInformationApp#39]
I think, defaults should always be based on how often a feature is needed.
I think that most people look at the exam results page more often than at the "Overview" page, since it changes more often.

Changing the default page to "Exams" would save some time and clicking.

**Comment by Bennik2000** [comment]
I don't like the idea of setting the defaut page to "Exams". IMO the "overview" page should be the first page to show, as it gives a brief overview of your grades in general. 

However, I also do not like to navigate to the "exams" page every single time. 

I can think of saving the last page the user has seen and then setting this as default page. If the user did not navigate to the dualis page before, the "overview" page is shown. Else the "overview" or the "exams" page are shown, depending on the last state.

**Comment by Bennik2000** [comment]
> I think, defaults should always be based on how often a feature is needed.

It would be nice to have some analytics and telemetry data. Then we know what part of the app is used. However, a potential telemetry function has to be DSGVO conform and it should be possible to deactivate it.

**Comment by Bennik2000** [comment]
Implemented in #41
