### ISSUE TITLE
Notification setting is not taken into account

### ISSUE THREAD

**Issue by Gregorie** [Bennik2000/DHBWStudentInformationApp#57]
## Expected Behavior
Schedule notifications should not been sent if they are turned off.

## Current Behavior
Schedule notifications are sent even if they are turned off.

## Steps to Reproduce
1. Install app
2. Import schedule
3. Go to settings in the app
4. Turn notifications off
5. Get notification in the evening :disappointed:

## Context (Environment)
-  Version 1.0.14
- Android 9

**Comment by Bennik2000** [comment]
Thanks for reporting, I'll look into this!

**Comment by Bennik2000** [comment]
Fixed this bug in 8a6d9c00806b69b98cb8e4da14fa4a5e46cdc0d9
