### ISSUE TITLE
"Export to calendar" is not working

### ISSUE THREAD

**Issue by Gregorie** [Bennik2000/DHBWStudentInformationApp#58]
## Expected Behavior
"Export to calendar" should provide the possibility to export the dates to a calendar application.

## Current Behavior
The "Export to calendar" function doesn't work.

## Steps to Reproduce
1. Go to "Dates"
2. Select some Database and year
3. Use "Export to calendar" function
4. "Choose the calendar to export the dates to:" is shown, but there are no applications listed.

![Screenshot from app](https://user-images.githubusercontent.com/5672294/95256930-d37d1680-0823-11eb-8064-a0e50e5cd3dd.jpeg)

## Context (Environment)
-  Version 1.0.14
- Android 9

**Comment by Bennik2000** [comment]
Did you allow the app to get access to the calendar?

**Comment by Bennik2000** [comment]
My investigation so far:
- I can not reproduce it with the app being in debug mode
- I can not reproduce it with the app being in relese mode
- I can reproduce it with the app being downloaded from the AppStore

**Comment by Gregorie** [comment]
![Screenshot_20201006-225500_Package installer.jpg](https://user-images.githubusercontent.com/5672294/95259289-4045e000-0827-11eb-8477-336e4a83f14b.jpg)

Yes, the permission is given.

And yes, there are calendars with write access.

Just tried it on three different devices. Even after resetting the app and granting the calendar permission before opening the app, there are no calendars visible.

**Comment by Bennik2000** [comment]
I was able to reproduce this issue and traced it back to an improper proguard configuration. More information is provided [here](https://github.com/builttoroam/device_calendar/issues/99): 

You can download an internal app version which contains a fix [here](https://play.google.com/apps/test/RQUSLEPQgPQ/ahAOU_83g38ToNYTAwLOCTTITFXh7jta1B01bBG_-TR_fpb_RCYu7HpI3WWFxCYcD_SPvZu8kDFcsPTbn--X8SzIKZ
)*

Could you try the updated version and let me know if it fixes your issue? 



(*) [Maybe you habe to enable the developer mode in the play store](https://www.android-user.de/entwickleroption-im-play-store-ermoeglicht-interne-app-freigabe/)

**Comment by Gregorie** [comment]
Yeah, now it works 👌
