### ISSUE TITLE
Landscape orientation for tablets

### ISSUE THREAD

**Issue by gregorsarnow** [Bennik2000/DHBWStudentInformationApp#60]
small suggestion for improvement :bulb:

## Expected Behavior
Landscape orientation should be available for tablets.

## Current Behavior
Landscape orientation is not available.

**Comment by Bennik2000** [comment]
This feature is already implemented. 

What tablet do you use?

**Comment by Gregorie** [comment]
Ah, okay.

Then its a bug, only occuring if you start the app in landscape orientation (app has to be stopped before).
If you open the app in portrait orientation, it works.

However, if you open it in landscape mode, it automatically switches to portrait mode and blocks further rotations.

**Comment by Bennik2000** [comment]
I can't reproduce this issue. 

This are the steps I used for testing:
- Test 1:
  - Have the tablet in landscape mode
  - Start the app
  - (it opens in landscape mode)
  - Rotate the tablet to portrait mode
  - (Now the app is in portrait mode)

- Test 2: 
  - Have the tablet in portrait mode
  - Start the app
  - (it opens in portrait mode)
  - Rotate the tablet to landscape mode
  - (Now the app is in landscape mode)


Note that for both tests auto rotate is enabled. If it is disabled the app does not rotate (as expected): 
![grafik](https://user-images.githubusercontent.com/8039939/95299511-22f03080-087e-11eb-84ce-360a403e0a8b.png)

**Comment by Bennik2000** [comment]
@Gregorie can you give me some steps to reproduce this issue? Try to do it with version 1.1.2 and let me know if the issue still persists.

**Comment by Gregorie** [comment]
In v1.1.1 the issue is still present. As soon as the v1.1.2 is available in Play Store I will test it and upload a video

**Comment by Gregorie** [comment]
Just uploaded a [video](https://cloud.sarnow.dev/index.php/s/pLNc7BwAkYnw9gD). The bug still exists. Note that during the video I did not turn the tablet myself.

**Comment by Bennik2000** [comment]
Thanks for the video. 

What tablet do you use? Maybe the app thinks your tablet is a phone and does not allow landscape mode.
