### ISSUE TITLE
Kalender

### ISSUE THREAD

**Issue by kenji98** [Bennik2000/DHBWStudentInformationApp#76]
Nicht von jedem Studiengang werden die Termine angezeigt, obwohl in der Tabelle bei der DHBW Termine eingetragen sind.
Richtig gefiltert wurde auch ;)
Wie kann Ich das ändern ?

**Comment by Bennik2000** [comment]
Danke für die Rückmeldung!

Könntest Du ein paar weitere Infos geben (Welcher Studiengang bzw. welche Termine genau)?

**Comment by kenji98** [comment]
Studiengang wäre Bwl - Dlm - Logistik & Scm
Und generell alle Termine (Praxisphase, Theoriephase, Abgabe Pa2 etc.)

**Comment by Bennik2000** [comment]
Ah okay, danke

**Comment by Bennik2000** [comment]
Danke für die Info, ich habe den Fehler gefunden.

Die nächsten Tage wird ein Update für die App auf Android kommen (iOS leider etwas später), in der die Termine angezeigt werden.
