### ISSUE TITLE
iCal Kalender - keine Verbindung

### ISSUE THREAD

**Issue by AMThie** [Bennik2000/DHBWStudentInformationApp#99]
Hi, nutze die App auf iOS 14.4.2. 
Ich setze meinen Kalender öffentlich und kopiere den Link in die App. Nachdem ich dann auf die Kalenderansicht wechsle, kommt immer die Meldung „Keine Verbindung!“. 
Weiß jemand, wie ich das fixen kann?

**Comment by Bennik2000** [comment]
Welchen Kalender möchtest Du denn in der App anzeigen lassen?

**Comment by AMThie** [comment]
Hi, sorry nicht explizit genannt: iCloud/iCal Kalender

**Comment by AMThie** [comment]
Gibt es eine Lösung?

**Comment by Bennik2000** [comment]
Ich arbeite momentan daran, bitte habe noch etwas Gedult. Der iCAL von Apple liefert die Kalendereinträge anders zurück als es die App erwartet.
